---
name: Bug report
about: Report a (firefox-specific) bug.
labels: bug
---

<!--

Hi and thanks for your interest.

This extension is a fork of the Video Speed Controller Chrome extension, with minor changes to make it work on Firefox.

Please search for already existing issues both in here, and upstream.

If the problem also occurs with the Chrome extension, it should be fixed there.  
Any bugs fixed on there will be available in Firefox too.

Upstream Chromium extension: https://github.com/igrigorik/videospeed

-->





<!--- Please keep the note below for others who read your bug report. -->

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.
